project:
  type: website

execute:
  freeze: auto

website:
  site-url: "https://kayodehadilouadje.dev"
  open-graph: true
  cookie-consent:
    type: express
    style: headline
    palette: dark  
  title: "Kayode Hadilou ADJE"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hadilou
      - icon: twitter
        href: https://twitter.com/AHadilou
format:
  html:
    theme: cosmo
    css: styles.css



